[package]
name = "synchronization_primitives"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(loom)'.dependencies]
loom = "0.6"

[dependencies]
atomic-wait = "1.1.0"
loom = "0.6"
